landingpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.savestatus, name='savestatus'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('landingpage.urls', 'landingpage'), namespace='landingpage')),
]

landingpage/models.py
from django.db import models


class Status(models.Model):
    body = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, blank=False)

    def __str__(self):
        return self.body

landingpage/forms.py
from django import forms


class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
    }

    body = forms.CharField(label='Add Status', required=True, max_length=300,
                           widget=forms.TextInput(attrs=attrs))

landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from django.utils.timezone import localtime, now

response = {}
active = 'active-page'

# Create your views here.
def index(request):
    status = Status.objects.all()
    response['status'] = status
    response['status_form'] = Status_Form
    response['story6'] = active

    html = 'landingpage/index.html'
    return render(request, html, response)

def profile(request):
    response = {'home': active}

    html = 'profilku/index.html'
    return render(request, html, response)

def about(request):
    response = {'about': active, 'title': 'About'}
    return render(request, 'profilku/about.html', response)

def savestatus(request):
    form = Status_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['body'] = request.POST['body']
        status = Status(body=response['body'], date=now)
        status.save()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

templates/landingpage/index.html
{% extends "profilku/head.html" %}
{% load staticfiles %}
{% block content %}
  <div class="grid-container">
    <div class="grid-x grid-margin-x align-center-middle text-center">
      <div class="cell medium-12 title"><h1>Hello, apa kabar?</h1></div>
    </div>
    <div class="grid-x grid-margin-x grid-margin-y align-center-middle text-center">
      <form action="{% url 'landingpage:savestatus' %}" method="POST">
          {% csrf_token %}
          {{status_form}}
          <input id="submit" type="submit" class="button" value="Submit">
      </form>
    </div>
    <div class="grid-x grid-margin-x grid-margin-y align-center-middle">
        {% for data in status %}
        <div class="cell medium-4 text-center mini-card">
            <h6>{{data.date.date}} | {{data.date.time}}</h6>
            <p>{{data.body}}</p>
        </div>
        {% endfor %}
    </div>


{% endblock %}

templates/profilku/about.html
{% extends "profilku/head.html" %}
{% load staticfiles %}
{% block content %}
<div class="grid-container">
  <div class="grid-x grid-margin-x align-center-middle text-center">
    <div class="cell medium-12 title">About Me</div>
  </div>
</div>
<div class="grid-x">
  <div class="cell medium-4 card-left text-center">
    <img src="{% static 'assets/my-portrait.jpg' %}" alt="My Portrait" width="250">
    <p>I’m an active, energetic,<br>
      and cheerful web developer</p>
    <div class="personal-info text-left">
      <h3>Personal</h3>
      Email : jeremiadelviero@gmail.com<br>
      Telephone : 087878058022<br>
      Location : Bekasi, Jawa Barat<br>
      Birthday Date : 7 January 2000
    </div>
  </div>
  <div class="cell medium-8 card-right">
    <div class="card-right-content">
      <h3>Experience:</h3>
      <div class="timeline">
        <div class="date-content grid-x grid-margin-x">
          <div class="date cell medium-3">2015 - 2016</div>
          <div class="content cell medium-8">
            <h5 class="experience-position">Rohkris SMAN 1 Bekasi - Vice Chairman</h5>
            <p>Managing weekly worship - Music Division</p>
          </div>
        </div>
      </div>
    </div>
    <div class="card-right-content">
      <h3>Education:</h3>
      <div class="timeline">
        <div class="date-content grid-x grid-margin-x">
          <div class="date cell medium-3">2017 - Now</div>
          <div class="content cell medium-8">
            <h5>Universitas Indonesia - Computer Science</h5>
          </div>
        </div>
        <div class="date-content grid-x grid-margin-x">
          <div class="date cell medium-3">2014 - 2017</div>
          <div class="content cell medium-8">
            <h5>SMAN 1 Bekasi</h5>
          </div>
        </div>
        <div class="date-content grid-x grid-margin-x">
          <div class="date cell medium-3">2011 - 2014</div>
          <div class="content cell medium-8">
            <h5>SMPN 3 Bekasi</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="card-right-content">
      <h3>Skill:</h3>
      <ul>
        <li>Python</li>
        <li>Java</li>
        <li>HTML</li>
        <li>CSS</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/profilku/head.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 6</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
  </head>
  <body>
    <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium"  data-toggle="responsive-menu">
      <button class="menu-icon dark" type="button" data-toggle="responsive-menu"></button>
    </div>

    <div class="top-bar stacked-for-medium" id="responsive-menu">
      <div class="top-bar-left">
        <ul class="menu vertical medium-horizontal">
          <li class="menu-text nama-brand" data-hide-for="small">JerDelviero</li>
        </ul>
      </div>
      <div class="top-bar-right medium-align-center">
        <ul class="dropdown menu vertical medium-horizontal tombol-menu align-middle" data-dropdown-menu>
          <li class="{{home}}"><a href="/profile/">Home</a></li>
          <li class="{{about}}"><a href="/about/">About</a></li>
          <li class="{{story6}}"><a href="/">Story 6</a></li>
        </ul>
      </div>
    </div>
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/profilku/index.html
{% extends "profilku/head.html" %}
{% load staticfiles %}
{% block content %}
    <div class="grid-container">
      <div class="grid-x grid-margin-x align-center-middle text-center">
        <div class="cell medium-12 title">Hello, my name is Jeremia Delviero!</div>
        <div class="cell medium-5"><img src="{% static 'assets/my-photo.png' %}"
          alt="My Photo" width="350"></div>
        <div class="cell medium-6 text-left caption">Currently majoring Computer Science in
          University of Indonesia.<br><br>
          I’m interested in Web Development and
          Software Engineering.</div>
      </div>
    </div>
{% endblock %}